Repository caucse-hercules/Tree-acT, pull requests merged in 2021-09, with the labels that each got.

#7 [Feature] Added commitlint and pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .husky/commit-msg
  README.md
  commitlint.config.js
  package.json
  yarn.lock
Labels: documentation, enhancement

#8 [Fix] delete checkNameSame Func's unused parameter and change conponentIndex1, componentIndex2 type let to const
  treeAct-extension/src/generateCode.ts
Labels: enhancement

#9 [Refactor] Merge webview types with common types and change type name …
  common/testData.ts
  common/types.ts
  treeAct-extension/src/test/suite/extension.test.ts
  treeAct-extension/src/treeActPanel.ts
  treeAct-extension/src/treeActTreeView.ts
  treeAct-view/src/components/Node.tsx
  treeAct-view/src/components/Tree.tsx
  treeAct-view/src/components/markdownRender.tsx
  treeAct-view/src/module/index.ts
  treeAct-view/src/module/tree.ts
  treeAct-view/src/types.tsx
Labels: refactor

#12 [Fix] add prettier pre-commit hook again
  .husky/pre-commit
  package.json
  yarn.lock
Labels: enhancement

#13 [Feature] change any type to TreeNode[]
  treeAct-extension/src/generateCode.ts
Labels: enhancement

#14 [Fix]change variable name componentIndex to ComponentIndexWith~
  treeAct-extension/src/generateCode.ts
Labels: enhancement

#15 [Feature] change undefined check way
  treeAct-extension/src/generateCode.ts
Labels: enhancement

#16 [Refactor] Clearer type property name and redux removal procedure
  common/testData.ts
  common/types.ts
  treeAct-extension/src/generateCode.ts
  treeAct-extension/src/treeActTreeView.ts
  treeAct-view/src/components/Node.tsx
  treeAct-view/src/components/Tree.tsx
  treeAct-view/src/module/tree.ts
Labels: refactor
